##############################################xx
name: Release

on:
  release:
    types:
      - published

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - id: setup
        uses: tombenke/py-gh-actions/.github/actions/setup@master

      - id: checkout
        uses: tombenke/py-gh-actions/.github/actions/checkout@master

      - name: Run the dockerfile linter
        run: task dockerfile-lint

      - name: Run Docker build task
        run: task build-docker

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker images
        run: task push-docker
